databases:
  - name: advance_manifesto_datastore
    databaseName: advance_manifesto_production
    plan: basic-256mb
    region: virginia
services:
  - type: web
    name: advance_manifesto_webstore
    runtime: ruby
    plan: starter
    region: virginia
    buildCommand: "./bin/build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - fromGroup: advance_manifesto_production_group
  - type: redis
    name: advance_manifesto_redis
    plan: free
    region: virginia
    maxmemoryPolicy: noeviction
    ipAllowList: []
  - type: worker
    name: advance_manifesto_sidekiq_worker
    runtime: ruby
    region: virginia
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails assets:clean
    startCommand: bundle exec sidekiq
    plan: starter
    envVars:
      - fromGroup: advance_manifesto_production_group

