default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= Rails.application.credentials.database.username %>
  password: <%= Rails.application.credentials.database.password %>

development:
  <<: *default
  database: advance_manifesto_development

test:
  <<: *default
  database: advance_manifesto_test

production:
  <<: *default
  database: advance_manifesto_production
